{% extends "base.phtml" %}
{% block title %}Add New User{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header">Add New User</h3>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<form action="/admin/create-user" method="post" autocomplete="off">
			<div class="form-group">
				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<div class="input-group-text">Username</div>
					</div>
					<input type="text" name="usernm" autocomplete="off"><br><br>
				</div>
				<p>Passwords must be at least 12 characters, contain 1 number, and 1 letter</p>
				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<div class="input-group-text">Password</div>
					</div>
					<input type="password" name="userpw" autocomplete="new-password"><br>
				</div>
				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<div class="input-group-text">Confirm</div>
					</div>
					<input type="password" name="userpwconf" autocomplete="new-password">
				</div>
			<div class="form-group">
			</div>
				<button type="submit" class="btn btn-default">Create</button>
			</div>
		</form>
	</div>
</div>
{% endblock %}
