{% extends "base.phtml" %}
{% block title %}Edit Doctrines{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
<script>
$(document).ready(function() {
	$('#doctrine-table').DataTable({
		order: [[1, "asc"], [0, "asc"]],
		bInfo: false,
		searching: true,
		responsive: true,
		pageLength: 25,
		language: {
			emptyTable: "There are no doctrines"
		}
	});
	$('#add-doctrine-button').click(function() {
		$('#add-doctrine-modal').modal();
	});
});
</script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header" id="title"><i class="fa fa-rocket fa-fw"></i> Edit Doctrines</h3>
		<button type="button" class="btn btn-success" id="add-doctrine-button">Add</button>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-md-9">
		<div class="table-responsive">
			<table class="table responsive table-striped table-condensed" id="doctrine-table">
				<thead>
					<tr>
						<th>Doctrine</th>
						<th>Location</th>
						<th>Target Stock</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
{% for result in doclist %}
					<tr>
						<td><a href="/list/{{result.listId}}">{{result.name}}</a></td>
						<td>{{result.structName}}</td>
						<td>{{result.target}}</td>
						<td>
							<form method="post" action="/admin/delete-doctrine/{{result.doctrine}}">
								<input type="submit" class="btn btn-xs btn-danger doctrine-delete-button no-padding" value="Remove">
							</form>
						</td>
					</tr>
{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
<div class="modal fade" id="add-doctrine-modal" role="dialog" data-backdrop="static">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4>Add Doctrine</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body">
				<form role="form" method="post" action="/admin/add-doctrine">
					<div class="form-group">
						<label for="list-select">List</label>
						<select class="form-control" name="doctrine-list">
{% for list in lists %}
							<option value="{{list.listId}}">{{list.name}}</option>
{% endfor %}
						</select>
					</div>
					<div class="form-group">
						<label for="struct-select">Location</label>
						<select class="form-control" name="doctrine-struct">
{% for struct in structs %}
							<option value="{{struct.structId}}">{{struct.structName}}</option>
{% endfor %}
						</select>
					</div>
					<div class="form-group">
						<label for="doctrine-target-qt">Target Quantity</label>
						<input type="text" name="doctrine-targetqt" class="form-control" value="10">
					</div>
					<div>
						<hr>
						<input type="submit" class="btn btn-success" value="Add">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}
