{% extends "base.phtml" %}
{% block title %}List Users{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
<script>
$(document).ready(function() {
    $('#usertable').DataTable({
        order: [[0, "asc"]],
        paging: true,
        pageLength: 25,
        bInfo: false,
        responsive: true,
        select: true
    });
} );
</script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header">List Users</h3>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="table-responsive">
			<table id="usertable" class="table responsive table-striped table-condensed">
				<thead>
					<tr>
						<th>UserID</th>
						<th>Username</th>
						<th>Name</th>
						<th>Created</th>
						<th>Last Login</th>
						<th>Admin</th>
						<th>Disabled</th>
					</tr>
				</thead>
				<tbody>
{% for result in userlist %}
					<tr>
						<td>{{result.userId}}</td>
						<td>{{result.username}}</td>
						<td>{{result.name}}</td>
						<td>{{result.dateCreated}}</td>
						<td>{{result.lastLogin}}</td>
						<td>{{result.admin}}</td>
						<td>{{result.disabled}}</td>
					</tr>
{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}
