{% extends "base.phtml" %}
{% block title %}Structure Auths{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
<script>
$(document).ready(function() {
    $('#authtable').DataTable({
        order: [[0, "asc"]],
        paging: true,
        pageLength: 25,
        bInfo: false,
        responsive: true,
        select: true
    });
} );
</script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header">Structure Auths</h3>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="table-responsive">
			<table id="authtable" class="table responsive table-striped table-condensed">
				<thead>
					<tr>
						<th>Region</th>
						<th>Structure</th>
						<th>User</th>
						<th>Character</th>
					</tr>
				</thead>
				<tbody>
{% for result in authlist %}
					<tr>
						<td>{{result.regionName}}</td>
						<td>{{result.structName}}</td>
						<td>{{result.username}}</td>
						<td>{{result.charName}}</td>
					</tr>
{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}
