{% extends "base.phtml" %}
{% block title %}Appraisal{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header"><i class="fa fa-calculator fa-fw"></i> Appraisal</h3>
		<hr>
	</div>
	<div class="col-sm-6">
		<form action="/appraisal" method="post">
			<div class="form-group">
				<textarea name="rawpaste" class="form-control" rows="10"></textarea>
			<div class="form-group">
			</div>
				<button type="submit" class="btn btn-default">Submit</button>
			</div>
		</form>
	</div>
	<div class="col-sm-6">
	</div>
</div>
{% endblock %}
