<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		
		<title>{% block title %}{% endblock %}</title>
		
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
		<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/startbootstrap-sb-admin@4.0.0/css/sb-admin.min.css">
		<link rel="stylesheet" type="text/css" href="/css/common.css">
{% block extrastyle %}{% endblock %}
	</head>
	<body class="fixed-nav sticky-footer bg-dark" id="page-top">
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
			<a class="navbar-brand" href="/">DIRT</a>
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expand="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav navbar-sidenav" id="topAccordion">
					<li class="nav-item" title="Dashboard">
						<a class="nav-link" href="/dashboard">
							<i class="fa fa-dashboard fa-fw"></i>
							<span class="nav-link-text">Dashboard</span>
						</a>
					</li>
					<li class="nav-item" title="Wallet">
						<a class="nav-link" href="/wallet">
							<i class="fa fa-credit-card fa-fw"></i>
							<span class="nav-link-text">My Wallet</span>
						</a>
					</li>
					<li class="nav-item" title="My Lists">
						<a class="nav-link" href="/my-lists">
							<i class="fa fa-list fa-fw"></i>
							<span class="nav-link-text">My Lists</span>
						</a>
					</li>
{% if admin %}
					<li class="nav-item" title="My Alerts">
						<a class="nav-link" href="/my-alerts">
							<i class="fa fa-bell-o fa-fw"></i>
							<span class="nav-link-text">My Alerts</span>
						</a>
					</li>
{% endif %}
					<li class="nav-item" title="Market Browser">
						<a class="nav-link" href="/browse">
							<i class="fa fa-bar-chart-o fa-fw"></i>
							<span class="nav-link-text">Market Browser</span>
						</a>
					</li>
					<li class="nav-item" title="Contracts">
						<a class="nav-link" href="/contracts">
							<i class="fa fa-handshake-o fa-fw"></i>
							<span class="nav-link-text">Contracts</span>
						</a>
					</li>
					<li class="nav-item" title="Doctrines">
						<a class="nav-link" href="/doctrines">
							<i class="fa fa-rocket fa-fw"></i>
							<span class="nav-link-text">Doctrine Stock</span>
						</a>
					</li>
{% if admin %}
					<li class="nav-item" title="Station Trading">
						<a class="nav-link" href="/station-trade">
							<i class="fa fa-exchange fa-rotate-90 fa-fw"></i>
							<span class="nav-link-text">Station Trading</span>
						</a>
					</li>
					<li class="nav-item" title="Import Analysis">
						<a class="nav-link" href="/import">
							<i class="fa fa-sign-in fa-fw"></i>
							<span class="nav-link-text">Import Analysis</span>
						</a>
					</li>
{% endif %}
					<li class="nav-item" title="Trade Analysis">
						<a class="nav-link" href="/trade">
							<i class="fa fa-sign-out fa-fw"></i>
							<span class="nav-link-text">Trade Analysis</span>
						</a>
					</li>
{% if admin %}
					<li class="nav-item" title="Appraisal">
						<a class="nav-link" href="/appraisal">
							<i class="fa fa-calculator fa-fw"></i>
							<span class="nav-link-text">Appraisal</span>
						</a>
					</li>
{% endif %}
					<li class="nav-item" title="Economic Reports">
						<a class="nav-link" href="/economic-reports">
							<i class="fa fa-line-chart fa-fw"></i>
							<span class="nav-link-text">Economic Reports</span>
						</a>
					</li>
					<li class="nav-item" title="Insurance">
						<a class="nav-link" href="/insurance">
							<i class="fa fa-medkit fa-fw"></i>
							<span class="nav-link-text">Insurance</span>
						</a>
					</li>
				</ul>
				<ul class="navbar-nav sidenav-toggler">
					<li class="nav-item">
						<a class="nav-link text-center" id="sidenavToggler">
							<i class="fa fa-angle-left fa-fw"></i>
						</a>
					</li>
				</ul>
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<form class="form-inline my-2 my-lg-0 mr-lg-2" action="/search" method="get">
							<div class="input-group">
								<input class="form-control autocomplete" type="text" id="search" name="q" placeholder="Search for item...">
								<span class="input-group-append">
									<button class="btn btn-primary" type="submit">
										<i class="fa fa-search"></i>
									</button>
								</span>
							</div>
						</form>
					</li>
					<li class="nav-item dropdown no-arrow mx-1">
						<a class="nav-link dropdown-toggle" id="notif-dropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<i class="fa fa-bell-o fa-fw"></i>
							<span class="badge badge-danger badge-counter" id="notif-counter"></span>
						</a>
						<div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="notif-dropdown">
							<h6 class="dropdown-header">Notifications</h6>
							<div id="notif-list">
								<!--a class="dropdown-item d-flex align-items-center" href="/user/notification?id=0">
									<div>
										<div class="small text-gray-500">December 12, 2019</div>
										<span class="font-weight-bold">A new monthly report is ready to download!</span>
									</div>
								</a-->
							</div>
							<a class="dropdown-item text-center small text-gray-500" href="/user/notifications">Show All</a>
						</div>
					</li>
					<li class="nav-item dropdown no-arrow mx-1">
						<a class="nav-link dropdown-toggle" id="user-dropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<i class="fa fa-user-circle fa-fw"></i>
						</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="user-dropdown">
							<a class="dropdown-item" href="/user/characters">Characters</a>
							{% if admin %}
							<a class="dropdown-item" href="/admin">Admin</a>
							{% endif %}
							<a class="dropdown-item" href="/user/change-password">Change Password</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="/logout">Logout</a>
						</div>
					</li>
				</ul>
			</div>
		</nav>
		<div class="content-wrapper">
			<div class="container-fluid">
{% if errormsg %}
<div class="row">
	<div class="col-sm-12">
		<h5 class="alert alert-danger">{{errormsg}}</h5>
		<hr>
	</div>
</div>
{% endif %}
{% if successmsg %}
<div class="row">
	<div class="col-sm-12">
		<h5 class="alert alert-success">{{successmsg}}</h5>
		<hr>
	</div>
</div>
{% endif %}
{% block content %}{% endblock %}
			</div>
			<footer class="sticky-footer">
				<div class="container">
					<div class="text-center">
						<small>&copy;2020 pagefault.dev, EVE Online and the EVE logo are the registered trademarks of CCP hf.</small>
					</div>
				</div>
			</footer>
		</div>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.bundle.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
		<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/startbootstrap-sb-admin@4.0.0/js/sb-admin.min.js"></script>
		<script type="text/javascript" src="/js/common.js"></script>
{% block extrahead %}{% endblock %}
{% block extrascript %}{% endblock %}
	</body>
</html>
