<script src="https://code.highcharts.com/stock/7.1/highstock.js"></script>
<script src="https://code.highcharts.com/stock/7.1/modules/exporting.js"></script>
<script src="https://code.highcharts.com/stock/7.1/modules/export-data.js"></script>
<script src="https://code.highcharts.com/stock/7.1/modules/drag-panes.js"></script>
<script src="https://code.highcharts.com/stock/7.1/indicators/indicators.js"></script>
<script type="text/javascript" src="/js/chart-theme.js"></script>
