{% extends "base.phtml" %}
{% block title %}Item Stock{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
<script>
$(document).ready(function() {
	$('#stockTable').DataTable({
		order: [[0, "asc"]],
		paging: false,
		bInfo: false,
		responsive: true,
		searching: true,
		select: true,
		bLengthChange: false
	});
} );
</script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header" id="title"><i class="fa fa-shopping-cart fa-fw"></i> Item Stock</h3>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="table-responsive">
			<table class="table responsive table-striped table-condensed" id="stockTable">
				<thead>
					<tr>
						<th>Type</th>
						<th>Available</th>
						<th>Target</th>
						<th>Need</th>
						<th>% Stocked</th>
						<th>Jita Sell</th>
						<th>Stg Sell</th>
						<th>Margin</th>
						<th>Tgt Price</th>
						<th>Curr Cap</th>
						<th>Tgt Cap</th>
					</tr>
				</thead>
				<tbody>
{% for result in stocklist %}
					<tr>
						<td><a class="open-in-game" data-typeid="{{result.typeid}}" href="#"><i class="fa fa-magnet fa-fw"></i></a> <a target="_blank" href="/browse?type={{result.typeid}}">{{result.typename}}</a></td>
						<td>{{ result.available | number_format(0) }}</td>
						<td>{{ result.target | number_format(0) }}</td>
						<td>{{ result.need | number_format(0) }}</td>
						<td>{{ result.goal | number_format(0) }}</td>
						<td>{{ result.jitasell | number_format(0) }}</td>
						<td>{{ result.stagingsell | number_format(0) }}</td>
						<td>{{ result.margin | number_format(0) }}</td>
						<td>{{ result.targetprice | number_format(0) }}</td>
						<td>{{ result.mktcap | number_format(0) }}</td>
						<td>{{ result.tgtcap | number_format(0) }}</td>
					</tr>
{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}
