{% extends "base.phtml" %}
{% block title %}{{listinfo.name}}{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
<script>
$(document).ready(function() {
	$('#item-table').DataTable({
		order: [[0, "asc"]],
		bInfo: false,
		searching: true,
		responsive: true,
		pageLength: 25,
		language: {
			emptyTable: "There are no items in this list"
		}
	});
	$('#delete-list-button').click(function() {
		$('#deleteListModal').modal();
	});
});
</script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-9">
		<h3><i class="fa fa-paste fa-fw"></i> {{listinfo.name}}</h3>
		<button type="button" class="btn btn-danger" id="delete-list-button">Delete</button>
		<hr>
		<div class="table-responsive">
			<table id="item-table" class="table responsive table-striped table-hover table-condensed" style="width:100%">
				<thead>
					<tr>
						<th>Item</th>
						<th>Qt</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
{% for item in listitems %}
					<tr>
						<td><a target="_blank" href="/browse?type={{item.typeId}}">{{item.typeName}}</a></td>
						<td>{{item.quantity}}</td>
						<td>
							<form method="post" action="/list/{{listinfo.listId}}/delete-item/{{item.typeId}}">
								<input type="submit" class="btn btn-xs btn-danger item-delete-button no-padding" value="Remove">
							</form>
						</td>
					</tr>
{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
	<div class="col-md-3">
	</div>
</div>
<div class="modal fade" id="deleteListModal" role="dialog" data-backdrop="static">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4>Confirm Delete</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body">
				<form role="form" method="post" action="/list/{{listinfo.listId}}/delete-list">
					<div>
						<p>Are you sure you want to delete this list?</p>
						<input type="submit" class="btn btn-danger" value="Confirm">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}
