{% extends "base.phtml" %}
{% block title %}My Lists{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
<script>
$(document).ready(function() {
	$('#list-table').DataTable({
		order: [[0, "asc"]],
		bInfo: false,
		responsive: true,
		searching: true,
		pageLength: 25,
		language: {
			emptyTable: "You have no lists"
		}
	});
	$('#add-list-button').click(function() {
		$('#addListModal').modal();
	});
});
</script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-9">
		<h3><i class="fa fa-list fa-fw"></i> My Lists</h3>
		<button type="button" class="btn btn-success" id="add-list-button">Add</button>
		<hr>
		<div class="table-responsive">
			<table id="list-table" class="table responsive table-striped table-hover table-condensed" style="width:100%">
				<thead>
					<tr>
						<th>Name</th>
					</tr>
				</thead>
				<tbody>
{% for result in data %}
					<tr>
						<td><a href="/list/{{result.listId}}">{{result.name}}</a></td>
					</tr>
{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
	<div class="col-md-3">
	</div>
</div>
<div class="modal fade" id="addListModal" role="dialog" data-backdrop="static">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4>Add New List</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body">
				<form role="form" method="post" action="/my-lists">
					<div class="form-group">
						<label for="list-add-name">Name</label>
						<input type="text" name="list-add-name" class="form-control">
					</div>
					<div class="form-group">
						<label for="list-add-input">Input</label>
						<textarea name="list-add-input" class="form-control" rows="5"></textarea>
					</div>
					<div>
						<hr>
						<input type="submit" class="btn btn-success" value="Add">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock %}
