{% extends "base.phtml" %}
{% block title %}My Lists{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
<script src="/js/lists.js"></script>
<script>
$(function() {
	myListsLoad();
})
</script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<h3><i class="fa fa-list fa-fw"></i> My Lists</h3>
		<hr>
		<table id="list-table" class="table responsive table-striped table-hover table-condensed" style="width:100%">
		</table>
	</div>
</div>
<div class="modal fade" id="addListModal" role="dialog" data-backdrop="static">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4>Add New List</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body">
				<form role="form">
					<div class="form-group">
						<label for="list-add-name">Name</label>
						<input type="text" id="list-add-name" class="form-control">
					</div>
					<div class="form-group">
						<label for="list-add-visibility">Visibility</label>
						<select id="list-add-visibility" class="form-control">
							<option value="0">Private</option>
							<option value="1">Public</option>
						</select>
					</div>
					<div>
						<hr>
						<button type="submit" id="list-add-button" class="btn btn-success" data-dismiss="modal">Add</button>
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="editListModal" role="dialog" data-backdrop="static">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4>Edit List</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body">
				<form role="form">
					<input type="hidden" id="list-edit-id">
					<div class="form-group">
						<label for="list-edit-name">Name</label>
						<input type="text" id="list-edit-name" class="form-control">
					</div>
					<div class="form-group">
						<label for="list-edit-visibility">Visibility</label>
						<select id="list-edit-visibility" class="form-control">
							<option value="0">Private</option>
							<option value="1">Public</option>
						</select>
					</div>
					<div>
						<hr>
						<button type="submit" id="list-edit-button" class="btn btn-success" data-dismiss="modal">Save</button>
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="deleteListModal" role="dialog" data-backdrop="static">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4>Confirm Delete</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body">
				<form role="form">
					<div>
						<p>Are you sure you want to delete the select list(s)?</p>
						<button type="submit" id="list-delete-button" class="btn btn-danger" data-dismiss="modal">Confirm</button>
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}
