<option value="0">All Regions</option>
<optgroup label="Alliance">
	<option value="10000023">Pure Blind</option>
</optgroup>
<optgroup label="Winter Co">
	<option value="10000015">Venal</option>
	<option value="10000010">Tribute</option>
	<option value="10000003">Vale of the Silent</option>
	<option value="10000055">Branch</option>
	<option value="10000045">Tenal</option>
	<option value="10000029">Geminate</option>
</optgroup>
<!--optgroup label="FIRE">
	<option value="10000009">Insmother</option>
	<option value="10000005">Detorid</option>
	<option value="10000006">Wicked Creek</option>
	<option value="10000008">Scalding Pass</option>
	<option value="10000007">Cache</option>
</optgroup-->
<!--optgroup label="PanFam">
	<option value="10000018">The Spire</option>
	<option value="10000034">The Kalevala Expanse</option>
	<option value="10000027">Etherium Reach</option>
	<option value="10000066">Perrigen Falls</option>
	<option value="10000040">Oasa</option>
	<option value="10000053">Cobalt Edge</option>
	<option value="10000013">Malpais</option>
</optgroup-->
<optgroup label="Hisec Hubs">
	<option value="10000002">The Forge (Jita)</option>
<!--	<option value="10000043">Domain (Amarr)</option>
	<option value="10000032">Sinq Liasion (Dodixie)</option>
	<option value="10000030">Heimatar (Rens)</option>-->
</optgroup>
<!--optgroup label="Other">
</optgroup-->
