<option value="0">All Regions</option>
<optgroup label="Warfront">
	<option value="10000060">Delve</option>
	<option value="10000050">Querious</option>
	<option value="10000063">Period Basis</option>
</optgroup>
<optgroup label="Alliance">
	<option value="10000039">Esoteria</option>
	<option value="10000059">Paragon Soul</option>
</optgroup>
<optgroup label="Coalition">
	<option value="10000031">Impass</option>
	<option value="10000056">Feythabolis</option>
	<option value="10000014">Catch</option>
	<option value="10000025">Immensea</option>
	<option value="10000061">Tenerifis</option>
	<option value="10000062">Omist</option>
</optgroup>
<optgroup label="Greater Allies">
	<option value="10000005">Detorid</option>
	<option value="10000009">Insmother</option>
	<option value="10000006">Wicked Creek</option>
	<option value="10000008">Scalding Pass</option>
</optgroup>
<optgroup label="Hisec Hubs">
	<option value="10000002">The Forge (Jita)</option>
	<option value="10000043">Domain (Amarr)</option>
	<option value="10000032">Sinq Liasion (Dodixie)</option>
	<option value="10000030">Heimatar (Rens)</option>
</optgroup>
<optgroup label="Other">
	<option value="10000022">Stain</option>
	<option value="10000007">Cache</option>
	<option value="10000012">Curse</option>
	<option value="10000054">Aridia</option>
</optgroup>
