{% extends "base.phtml" %}
{% block title %}Wallet{% endblock %}
{% block extrahead %}
{% include 'table-libs.phtml' %}
<script type="text/javascript" src="js/wallet.js"></script>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header"><i class="fa fa-credit-card fa-fw"></i> Wallet</h3>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default no-border">
			<div class="panel-body no-padding">
				<ul class="nav nav-tabs" role="tablist">
					<li class="nav-item">
						<a class="nav-link active" id="transactions-label" href="#transactions" data-toggle="tab" role="tab" aria-controls="transactions" aria-selected="true">Transactions</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="journal-label" href="#journal" data-toggle="tab" role="tab" aria-controls="journal" aria-selected="false">Journal</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="sell-orders-label" href="#sell-orders" data-toggle="tab" role="tab" aria-controls="sell-orders" aria-selected="false">Sell Orders</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="buy-orders-label" href="#buy-orders" data-toggle="tab" role="tab" aria-controls="buy-orders" aria-selected="false">Buy Orders</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="contracts-label" href="#contracts" data-toggle="tab" role="tab" aria-controls="contracts" aria-selected="false">Contracts</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="roi-label" href="#roi" data-toggle="tab" role="tab" aria-controls="roi" aria-selected="false">Item ROI</a>
					</li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane fade tab-border mb-3 show active" id="transactions" aria-labelledby="transactions-label">
						<div class="table-responsive">
							<table id="transactions-table" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
					<div class="tab-pane fade tab-border mb-3" id="journal" aria-labelledby="journal-label">
						<div class="table-responsive">
							<table id="journal-table" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
					<div class="tab-pane fade tab-border mb-3" id="sell-orders" aria-labelledby="sell-orders-label">
						<div class="table-responsive">
							<table id="sell-orders-table" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
					<div class="tab-pane fade tab-border mb-3" id="buy-orders" aria-labelledby="buy-orders-label">
						<div class="table-responsive">
							<table id="buy-orders-table" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
					<div class="tab-pane fade tab-border mb-3" id="contracts" aria-labelledby="contracts-label">
						<div class="table-responsive">
							<table id="contracts-table" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
					<div class="tab-pane fade tab-border mb-3" id="roi" aria-labelledby="roi-label">
						<div class="table-responsive">
							<table id="roi-table" class="table responsive table-striped table-hover table-condensed" style="width:100%"></table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
