{% extends "base.phtml" %}
{% block title %}Change Password{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header">Change Password</h3>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<form action="/user/change-password" method="post" autocomplete="off">
			<div class="form-group">
				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<div class="input-group-text">Old</div>
					</div>
					<input type="password" name="userpw" autocomplete="off"><br><br>
				</div>
				<p>Passwords must be at least 12 characters, contain 1 number, and 1 letter</p>
				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<div class="input-group-text">New</div>
					</div>
					<input type="password" name="userpwnew" autocomplete="new-password"><br>
				</div>
				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<div class="input-group-text">Confirm</div>
					</div>
					<input type="password" name="userpwnewconf" autocomplete="new-password">
				</div>
			<div class="form-group">
			</div>
				<button type="submit" class="btn btn-default">Submit</button>
			</div>
		</form>
	</div>
</div>
{% endblock %}
