{% extends "base.phtml" %}
{% block title %}Characters{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header" id="title">Characters</h3>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<div class="table-responsive">
			<table class="table responsive table-striped table-condensed">
{% for result in charlist %}
	{% if result.charId == charid %}
				<tr class="highlight">
	{% else %}
				<tr>
	{% endif %}
					<td><img src="https://imageserver.eveonline.com/Character/{{result.charId}}_64.jpg"></td>
					<td>{{result.charName}}</td>
					<td>
						<form action="/user/characters" method="post">
							<input type="hidden" id="charId" name="charId" value="{{result.charId}}">
							<button type="submit" class="btn btn-primary">Set Active</button>
						</form>
					</td>
					<td>
						<form action="/sso-auth/unlink" method="post">
							<input type="hidden" id="charId" name="charId" value="{{result.charId}}">
							<button type="submit" class="btn btn-primary">Unlink</button>
						</form>
					</td>
				</tr>
{% endfor %}
			</table>
		</div>
		<form action="/sso-auth/link" method="post">
			<button type="submit" class="btn btn-primary">Link a character to this account (EVE SSO)</button>
		</form>
	</div>
	<div class="col-md-3">
	</div>
	<div class="col-md-3">
	</div>
</div>
{% endblock %}
