{% extends "base.phtml" %}
{% block title %}Notifications{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h3 class="page-header" id="title">Notifications</h3>
		<hr>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="btn-toolbar" role="toolbar">
			<div class="btn-group btn-group-sm ml-2 mr-2" role="group">
				<form action="/user/notifications" method="post">
					<input type="hidden" id="notifId" name="notifId" value="ack-all">
					<button type="submit" class="btn btn-primary">Acknowledge All</button>
				</form>
				<form action="/user/notifications" method="post">
					<input type="hidden" id="notifId" name="notifId" value="del-all">
					<button type="submit" class="btn btn-primary">Delete All</button>
				</form>
			</div>
		</div>
		<br />
		<div class="table-responsive">
			<table class="table responsive table-striped table-condensed">
{% for result in notiflist %}
				<tr>
					<td class="p-1">{{result.time}}</td>
					<td class="p-1">{{result.text}}</td>
					<td class="p-1">
{% if result.acknowledged == 0 %}
						<form action="/user/notifications" method="post">
							<input type="hidden" id="notifId" name="notifId" value="{{result.notifId}}">
							<button type="submit" class="btn btn-sm btn-primary">Acknowledge</button>
						</form>
{% endif %}
					</td>
				</tr>
{% endfor %}
			</table>
		</div>
	</div>
</div>
{% endblock %}
